
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Muhammad Rizal Nur F
 */
public class BP1_M4_P1_Rizal extends javax.swing.JFrame {

    /**
     * Creates new form BP1_M4_P1_Rizal
     */
    public BP1_M4_P1_Rizal() {
        initComponents();
    }
    
       private void Login() {
        String user = jTextField1.getText();
        String pass = jTextField2.getText();
        String level = jComboBox1.getSelectedItem().toString();

        // Validasi untuk username tidak diisi
        if (user.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username harus diisi", "Login Message", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi untuk password tidak diisi
        if (pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password harus diisi", "Login Message", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi untuk level login
        if (level.equals("Pilih Level")) {
            JOptionPane.showMessageDialog(null, "Level harus dipilih", "Login Message", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Kondisi login berdasarkan level
        if (user.equals("admin") && pass.equals("admin111") && level.equals("Admin")) {
            JOptionPane.showMessageDialog(null, "Login sukses sebagai Admin", "Login Message", JOptionPane.INFORMATION_MESSAGE);
        } else if (user.equals("user") && pass.equals("user123") && level.equals("User")) {
            JOptionPane.showMessageDialog(null, "Login sukses sebagai User", "Login Message", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Username, Password, atau Level salah", "Login Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BP1_M4_P1_Rizal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BP1_M4_P1_Rizal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BP1_M4_P1_Rizal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BP1_M4_P1_Rizal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void n() {
                new BP1_M4_P1_Rizal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
